name: macOS Tests
on:
  workflow_dispatch:
  push:
    branches: [main, 'release/*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    name: Unit Tests (macOS)
    timeout-minutes: 60
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Run Unit Tests
        uses: ./.github/actions/tests/run-unit-tests

  cli-test:
    name: CLI Tests (macOS)
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node Dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Run CLI Tests
        uses: ./.github/actions/tests/run-cli-tests

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: always()
        with:
          check_name: CLI Test Results (macOS)
          files: packages/bruno-tests/collection/junit.xml
          comment_mode: off
          check_run: false
